/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

public class App {


    public static void checkSemicolons(Path filePath) throws IOException {
        FileReader fileReader = new FileReader(filePath.toFile());
        BufferedReader bufferedReader = new BufferedReader(fileReader);
        String line;
        int lineNumber = 1;
        StringBuilder errorBuilder = new StringBuilder();
        while ((line = bufferedReader.readLine()) != null) {
            line = line.trim();
            if (line.isEmpty()) {
                lineNumber++;
                continue;
            }
            if (line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else")) {
                lineNumber++;
                continue;
            }
            if (!line.endsWith(";")) {
                errorBuilder.append("Line ").append(lineNumber).append(": Missing semicolon.\n");
            }
            lineNumber++;
        }
        System.out.print(errorBuilder.toString());
    }

    public static void main(String[] args) {
        Path filePath = Paths.get("./app/src/main/resources/gates.js");
        try {
            checkSemicolons(filePath);
        } catch (IOException e) {
            System.out.println("An error occurred while reading the file.");
            e.printStackTrace();
        }
    }
}


