/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant fancyPlace = new Restaurant("The Fancy Place", 4, "$$$");
        Review review1 = new Review("Great food and service!", "John Smith", 5,"The Fancy Place", 4, "$$$");
        Review review2 = new Review("Terrible experience.", "Jane Doe", 1,"The Fancy Place", 4, "$$$");
        fancyPlace.addReview(review1);
        fancyPlace.addReview(review2);
        System.out.println(fancyPlace);

    }
}
