/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package class2;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class Library {
    public static int[] roll(int n) {
        if (n <= 0) {
            return new int[0];
        }
        int[] rolls = new int[n];
        for (int i = 0; i < n; i++) {
            rolls[i] = (int) (Math.random() * 6) + 1;
        }
        System.out.println(Arrays.toString(rolls));
        return rolls;
    }
    public static boolean containsduplicates(int[] arr) {
        Arrays.sort(arr);
        for (int i = 0; i < arr.length - 1; i++) {
            if (arr[i] == arr[i+1]) {
                return true;
            }
        }
        return false;
    }
    public static double calculateAverage(int[] arr) {
        int sum = 0;
        for (int i = 0; i < arr.length; i++) {
            sum += arr[i];
        }
        double average = (double)sum / arr.length;
        return average;
    }

    public static int[] getLowestAverageArray(int[][] arr) {
        int[] lowestAverageArray = null;
        double lowestAverage = Double.MAX_VALUE;
        for (int[] innerArray : arr) {
            int sum = 0;
            for (int num : innerArray) {
                sum += num;
            }
            double average = (double) sum / innerArray.length;
            if (average < lowestAverage) {
                lowestAverage = average;
                lowestAverageArray = innerArray;
            }}
        return lowestAverageArray;
    }

}
