/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();

    @Test
    void testNoErrors() {
        Path filePath = Paths.get("./app/src/test/resources/noerrors.js");
        String errorMessage = classUnderTest.checkSemicolons(filePath);
        assertEquals("", errorMessage);
    }

    @Test
    void testOneError() {
        Path filePath = Paths.get("./app/src/test/resources/oneerror.js");
        String errorMessage = classUnderTest.checkSemicolons(filePath);
        assertEquals("", errorMessage);
    }

    @Test
    void testFewErrors() {
        Path filePath = Paths.get("./app/src/test/resources/fewerrors.js");
        String errorMessage = classUnderTest.checkSemicolons(filePath);
        assertEquals("", errorMessage);
    }

    @Test
    void testManyErrors() {
        Path filePath = Paths.get("./app/src/test/resources/manyerrors.js");
        String errorMessage = classUnderTest.checkSemicolons(filePath);
        assertEquals("", errorMessage);
    }

    @Test
    void testEmptyFile() {
        Path filePath = Paths.get("./app/src/test/resources/empty.js");
        String errorMessage = classUnderTest.checkSemicolons(filePath);
        assertEquals("", errorMessage);
    }
}
